apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    run: node-app
spec:
  ports:
    - port: 3000
      name: main
      protocol: TCP
      targetPort: 3000
  selector:
    run: node-app
  type: NodePort
